config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#index'
  resources :sessions, only: :index

  get "/logout" => 'sessions#destroy', as: :logout
  get "/auth/:provider/callback" => 'sessions#create'
end

app/models/sent_message.rb
# This file is intended to handle sent messages of user.
# Search Sent Message
#
# Created At: 04-Feb-2015
# Author : Atharva System
# Copyright:: Copyright (c) 2012-2015 Atharva System.

class SentMessage < ActiveRecord::Base
  belongs_to :user

  validates :message_id, :uniqueness => true

  def self.search(search)
    if search
      where('subject LIKE ?', "%#{search}%")
    else
      where('1=1')
    end
  end

  def to_name_or_email
    to_name || to_email
  end
end

app/models/user.rb
# This file is intended to handle users authenticated using omniauth.
# Validates user's access token
# Sent Messages Synchronization
#
# Created At: 04-Feb-2015
# Author : Atharva System
# Copyright:: Copyright (c) 2012-2015 Atharva System.

class User < ActiveRecord::Base
  has_many :sent_messages

  validates :email, presence: true, format: {:with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/}, uniqueness: true
  validates :provider, presence: true
  validates :expires_at, presence: true

  def self.create_using_omniauth(auth)
    user = User.where(uid: auth['uid']).first_or_initialize
    user.provider = auth['provider']
    user.email = auth['extra']['raw_info']['email']
    user.access_token = auth['credentials']['token']
    user.expires_at = Time.at(auth['credentials']['expires_at']).to_datetime
    user.save
    return user
  end

  def token_expired?
    expires_at < Time.now
  end

  def sync_sent_messages
    if self.token_expired?
      Rails.logger.info "-- %s --" % [I18n.t(:token_expired, :user => self.email)]
      return false
    end
    last_sent_message = self.sent_messages.last
    imap = Net::IMAP.new('imap.gmail.com', 993, usessl = true, certs = nil, verify = false)
    imap.authenticate('XOAUTH2', self.email, self.access_token)

    mailbox_all_mail = imap.list('', '*').find{|mb| mb.attr.include?(:Sent)}
    imap.examine(mailbox_all_mail.name)

    imap.search(["FROM", "me"]).reverse[0,10].reverse.each do |message_id|
      next if last_sent_message and message_id <= last_sent_message.message_id
      envelope = imap.fetch(message_id, "ENVELOPE")[0].attr["ENVELOPE"]
      sent_message = self.sent_messages.create() do |sent|
        sent.message_id = message_id
        sent.to_name = envelope.to[0].name
        sent.to_email = "#{envelope.to[0].mailbox}@#{envelope.to[0].host}"
        sent.subject = envelope.subject
        sent.sent_date = envelope.date.to_datetime
      end
    end
  rescue Net::IMAP::NoResponseError => e
    p e.message
    return false
  end
end

app/controllers/application_controller.rb
# This file is intended to handle current user and check token expiration.
#
# Created At: 04-Feb-2015
# Author : Atharva System
# Copyright:: Copyright (c) 2012-2015 Atharva System.

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :logged_in?, :current_user

  before_filter :set_current_user

  def check_token_expired?
    if logged_in?
      if @current_user.token_expired?
        session.delete(:user_id)
        redirect_to root_path
      end
    end
  end

  def logged_in?
    !!@current_user
  end

  def current_user
    return User.find(session[:user_id]) if session[:user_id]
    return nil
  rescue ActiveRecord::RecordNotFound => e
    return nil
  end

  private

  def set_current_user
    @current_user ||= current_user
  end
end

app/controllers/sessions_controller.rb
# This file is intended to handle sessions for the application.
# index: List sent messages of current user.
# create: create user authenticated by omniauth and synchronizes sent messages.
# oauth_failure: redirects user to home page when authentication fails from omniauth.
# destroy: destroy the session of a user and redirects to home page.
#
# Created At: 04-Feb-2015
# Author : Atharva System
# Copyright:: Copyright (c) 2012-2015 Atharva System.

class SessionsController < ApplicationController
  before_filter :check_token_expired?, :except => [:index]

  def index
    if logged_in?
      # @current_user.sync_sent_messages
      @sent_messages = @current_user.sent_messages.search(params[:search]).order(message_id: :desc).limit(10)
    end
  end

  def create
    user = User.create_using_omniauth(request.env['omniauth.auth'])
    flash[:success] = t(:authenticated)
    session[:user_id] = user.id
    current_user.sync_sent_messages
  rescue OAuth2::Error => e
    flash[:error] = e.message
  ensure
    redirect_to root_path
  end

  def oauth_failure
    redirect_to root_path
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = t(:logout)
    redirect_to(root_path)
  end
end

app/helpers/application_helper.rb
# This file is intended to handle helper methods.
# For alert flash messages
# For datetime format
#
# Created At: 04-Feb-2015
# Author : Atharva System
# Copyright:: Copyright (c) 2012-2015 Atharva System.

module ApplicationHelper
  def alert_class_for(flash_type)
    {
        :success => 'alert-success',
        :error => 'alert-danger',
        :alert => 'alert-warning',
        :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def datetime_format(date)
    date.strftime("%b %d")
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div class="alert <%= alert_class_for(type) %> fade in">
      <button class="close" data-dismiss="alert" onClick="$('.alert').fadeOut();" style="border: none; background: transparent;">×</button>
      <%= message %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!--
# This file contains main application layout.
# includes javascripts, stylesheets and view part
#
# Created At: 04-Feb-2015
# Author : Atharva System
# Copyright:: Copyright (c) 2012-2015 Atharva System.
-->

<!DOCTYPE html>
<html>
<head>
  <title>SentMailViewer</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= render(partial: "layouts/flash_messages", flash: flash) unless flash.empty? %>
  <div class="row">
    <div class="twelve columns">
      <%= content_tag(:div, raw("Welcome: #{auto_link(@current_user.email)} - #{link_to("Logout!", logout_path, :data => {:confirm => "Are you sure to logout ?"})}"), :style => "float:right") if logged_in? %>
      <h1>Sent Mail Viewer</h1>
      <%= link_to(image_tag("sign-in-button.png", :style => "height: 40px"), '/auth/google_oauth2', :id => 'sign-in-button') unless logged_in? %>
      <%= yield %>
    </div>
  </div>
</div>
<%= javascript_include_tag 'common', 'data-turbolinks-track' => true %>
</body>
</html>